import type { PrismaClient } from '@prisma/client';

/**
 * City reference data — converted from the phpMyAdmin JSON export.
 * `gov` matches `Governorate.code` (zero-padded original governorate id).
 */
export const CITIES: Array<{
  gov: string;
  name: string;
  nameAr: string;
}> = [
  { gov: "01", name: "15 May", nameAr: "15 مايو" },
  { gov: "01", name: "Al Azbakeyah", nameAr: "الازبكية" },
  { gov: "01", name: "Al Basatin", nameAr: "البساتين" },
  { gov: "01", name: "Tebin", nameAr: "التبين" },
  { gov: "01", name: "El-Khalifa", nameAr: "الخليفة" },
  { gov: "01", name: "El darrasa", nameAr: "الدراسة" },
  { gov: "01", name: "Aldarb Alahmar", nameAr: "الدرب الاحمر" },
  { gov: "01", name: "Zawya al-Hamra", nameAr: "الزاوية الحمراء" },
  { gov: "01", name: "El-Zaytoun", nameAr: "الزيتون" },
  { gov: "01", name: "Sahel", nameAr: "الساحل" },
  { gov: "01", name: "El Salam", nameAr: "السلام" },
  { gov: "01", name: "Sayeda Zeinab", nameAr: "السيدة زينب" },
  { gov: "01", name: "El Sharabeya", nameAr: "الشرابية" },
  { gov: "01", name: "Shorouk", nameAr: "مدينة الشروق" },
  { gov: "01", name: "El Daher", nameAr: "الظاهر" },
  { gov: "01", name: "Ataba", nameAr: "العتبة" },
  { gov: "01", name: "New Cairo", nameAr: "القاهرة الجديدة" },
  { gov: "01", name: "El Marg", nameAr: "المرج" },
  { gov: "01", name: "Ezbet el Nakhl", nameAr: "عزبة النخل" },
  { gov: "01", name: "Matareya", nameAr: "المطرية" },
  { gov: "01", name: "Maadi", nameAr: "المعادى" },
  { gov: "01", name: "Maasara", nameAr: "المعصرة" },
  { gov: "01", name: "Mokattam", nameAr: "المقطم" },
  { gov: "01", name: "Manyal", nameAr: "المنيل" },
  { gov: "01", name: "Mosky", nameAr: "الموسكى" },
  { gov: "01", name: "Nozha", nameAr: "النزهة" },
  { gov: "01", name: "Waily", nameAr: "الوايلى" },
  { gov: "01", name: "Bab al-Shereia", nameAr: "باب الشعرية" },
  { gov: "01", name: "Bolaq", nameAr: "بولاق" },
  { gov: "01", name: "Garden City", nameAr: "جاردن سيتى" },
  { gov: "01", name: "Hadayek El-Kobba", nameAr: "حدائق القبة" },
  { gov: "01", name: "Helwan", nameAr: "حلوان" },
  { gov: "01", name: "Dar Al Salam", nameAr: "دار السلام" },
  { gov: "01", name: "Shubra", nameAr: "شبرا" },
  { gov: "01", name: "Tura", nameAr: "طره" },
  { gov: "01", name: "Abdeen", nameAr: "عابدين" },
  { gov: "01", name: "Abaseya", nameAr: "عباسية" },
  { gov: "01", name: "Ain Shams", nameAr: "عين شمس" },
  { gov: "01", name: "Nasr City", nameAr: "مدينة نصر" },
  { gov: "01", name: "New Heliopolis", nameAr: "مصر الجديدة" },
  { gov: "01", name: "Masr Al Qadima", nameAr: "مصر القديمة" },
  { gov: "01", name: "Mansheya Nasir", nameAr: "منشية ناصر" },
  { gov: "01", name: "Badr City", nameAr: "مدينة بدر" },
  { gov: "01", name: "Obour City", nameAr: "مدينة العبور" },
  { gov: "01", name: "Cairo Downtown", nameAr: "وسط البلد" },
  { gov: "01", name: "Zamalek", nameAr: "الزمالك" },
  { gov: "01", name: "Kasr El Nile", nameAr: "قصر النيل" },
  { gov: "01", name: "Rehab", nameAr: "الرحاب" },
  { gov: "01", name: "Katameya", nameAr: "القطامية" },
  { gov: "01", name: "Madinty", nameAr: "مدينتي" },
  { gov: "01", name: "Rod Alfarag", nameAr: "روض الفرج" },
  { gov: "01", name: "Sheraton", nameAr: "شيراتون" },
  { gov: "01", name: "El-Gamaleya", nameAr: "الجمالية" },
  { gov: "01", name: "10th of Ramadan City", nameAr: "العاشر من رمضان" },
  { gov: "01", name: "Helmeyat Alzaytoun", nameAr: "الحلمية" },
  { gov: "01", name: "New Nozha", nameAr: "النزهة الجديدة" },
  { gov: "01", name: "Capital New", nameAr: "العاصمة الإدارية" },
  { gov: "02", name: "Giza", nameAr: "الجيزة" },
  { gov: "02", name: "Sixth of October", nameAr: "السادس من أكتوبر" },
  { gov: "02", name: "Cheikh Zayed", nameAr: "الشيخ زايد" },
  { gov: "02", name: "Hawamdiyah", nameAr: "الحوامدية" },
  { gov: "02", name: "Al Badrasheen", nameAr: "البدرشين" },
  { gov: "02", name: "Saf", nameAr: "الصف" },
  { gov: "02", name: "Atfih", nameAr: "أطفيح" },
  { gov: "02", name: "Al Ayat", nameAr: "العياط" },
  { gov: "02", name: "Al-Bawaiti", nameAr: "الباويطي" },
  { gov: "02", name: "ManshiyetAl Qanater", nameAr: "منشأة القناطر" },
  { gov: "02", name: "Oaseem", nameAr: "أوسيم" },
  { gov: "02", name: "Kerdasa", nameAr: "كرداسة" },
  { gov: "02", name: "Abu Nomros", nameAr: "أبو النمرس" },
  { gov: "02", name: "Kafr Ghati", nameAr: "كفر غطاطي" },
  { gov: "02", name: "Manshiyet Al Bakari", nameAr: "منشأة البكاري" },
  { gov: "02", name: "Dokki", nameAr: "الدقى" },
  { gov: "02", name: "Agouza", nameAr: "العجوزة" },
  { gov: "02", name: "Haram", nameAr: "الهرم" },
  { gov: "02", name: "Warraq", nameAr: "الوراق" },
  { gov: "02", name: "Imbaba", nameAr: "امبابة" },
  { gov: "02", name: "Boulaq Dakrour", nameAr: "بولاق الدكرور" },
  { gov: "02", name: "Al Wahat Al Baharia", nameAr: "الواحات البحرية" },
  { gov: "02", name: "Omraneya", nameAr: "العمرانية" },
  { gov: "02", name: "Moneeb", nameAr: "المنيب" },
  { gov: "02", name: "Bin Alsarayat", nameAr: "بين السرايات" },
  { gov: "02", name: "Kit Kat", nameAr: "الكيت كات" },
  { gov: "02", name: "Mohandessin", nameAr: "المهندسين" },
  { gov: "02", name: "Faisal", nameAr: "فيصل" },
  { gov: "02", name: "Abu Rawash", nameAr: "أبو رواش" },
  { gov: "02", name: "Hadayek Alahram", nameAr: "حدائق الأهرام" },
  { gov: "02", name: "Haraneya", nameAr: "الحرانية" },
  { gov: "02", name: "Hadayek October", nameAr: "حدائق اكتوبر" },
  { gov: "02", name: "Saft Allaban", nameAr: "صفط اللبن" },
  { gov: "02", name: "Smart Village", nameAr: "القرية الذكية" },
  { gov: "02", name: "Ard Ellwaa", nameAr: "ارض اللواء" },
  { gov: "03", name: "Abu Qir", nameAr: "ابو قير" },
  { gov: "03", name: "Al Ibrahimeyah", nameAr: "الابراهيمية" },
  { gov: "03", name: "Azarita", nameAr: "الأزاريطة" },
  { gov: "03", name: "Anfoushi", nameAr: "الانفوشى" },
  { gov: "03", name: "Dekheila", nameAr: "الدخيلة" },
  { gov: "03", name: "El Soyof", nameAr: "السيوف" },
  { gov: "03", name: "Ameria", nameAr: "العامرية" },
  { gov: "03", name: "El Labban", nameAr: "اللبان" },
  { gov: "03", name: "Al Mafrouza", nameAr: "المفروزة" },
  { gov: "03", name: "El Montaza", nameAr: "المنتزه" },
  { gov: "03", name: "Mansheya", nameAr: "المنشية" },
  { gov: "03", name: "Naseria", nameAr: "الناصرية" },
  { gov: "03", name: "Ambrozo", nameAr: "امبروزو" },
  { gov: "03", name: "Bab Sharq", nameAr: "باب شرق" },
  { gov: "03", name: "Bourj Alarab", nameAr: "برج العرب" },
  { gov: "03", name: "Stanley", nameAr: "ستانلى" },
  { gov: "03", name: "Smouha", nameAr: "سموحة" },
  { gov: "03", name: "Sidi Bishr", nameAr: "سيدى بشر" },
  { gov: "03", name: "Shads", nameAr: "شدس" },
  { gov: "03", name: "Gheet Alenab", nameAr: "غيط العنب" },
  { gov: "03", name: "Fleming", nameAr: "فلمينج" },
  { gov: "03", name: "Victoria", nameAr: "فيكتوريا" },
  { gov: "03", name: "Camp Shizar", nameAr: "كامب شيزار" },
  { gov: "03", name: "Karmooz", nameAr: "كرموز" },
  { gov: "03", name: "Mahta Alraml", nameAr: "محطة الرمل" },
  { gov: "03", name: "Mina El-Basal", nameAr: "مينا البصل" },
  { gov: "03", name: "Asafra", nameAr: "العصافرة" },
  { gov: "03", name: "Agamy", nameAr: "العجمي" },
  { gov: "03", name: "Bakos", nameAr: "بكوس" },
  { gov: "03", name: "Boulkly", nameAr: "بولكلي" },
  { gov: "03", name: "Cleopatra", nameAr: "كليوباترا" },
  { gov: "03", name: "Glim", nameAr: "جليم" },
  { gov: "03", name: "Al Mamurah", nameAr: "المعمورة" },
  { gov: "03", name: "Al Mandara", nameAr: "المندرة" },
  { gov: "03", name: "Moharam Bek", nameAr: "محرم بك" },
  { gov: "03", name: "Elshatby", nameAr: "الشاطبي" },
  { gov: "03", name: "Sidi Gaber", nameAr: "سيدي جابر" },
  { gov: "03", name: "North Coast/sahel", nameAr: "الساحل الشمالي" },
  { gov: "03", name: "Alhadra", nameAr: "الحضرة" },
  { gov: "03", name: "Alattarin", nameAr: "العطارين" },
  { gov: "03", name: "Sidi Kerir", nameAr: "سيدي كرير" },
  { gov: "03", name: "Elgomrok", nameAr: "الجمرك" },
  { gov: "03", name: "Al Max", nameAr: "المكس" },
  { gov: "03", name: "Marina", nameAr: "مارينا" },
  { gov: "04", name: "Mansoura", nameAr: "المنصورة" },
  { gov: "04", name: "Talkha", nameAr: "طلخا" },
  { gov: "04", name: "Mitt Ghamr", nameAr: "ميت غمر" },
  { gov: "04", name: "Dekernes", nameAr: "دكرنس" },
  { gov: "04", name: "Aga", nameAr: "أجا" },
  { gov: "04", name: "Menia El Nasr", nameAr: "منية النصر" },
  { gov: "04", name: "Sinbillawin", nameAr: "السنبلاوين" },
  { gov: "04", name: "El Kurdi", nameAr: "الكردي" },
  { gov: "04", name: "Bani Ubaid", nameAr: "بني عبيد" },
  { gov: "04", name: "Al Manzala", nameAr: "المنزلة" },
  { gov: "04", name: "tami al'amdid", nameAr: "تمي الأمديد" },
  { gov: "04", name: "aljamalia", nameAr: "الجمالية" },
  { gov: "04", name: "Sherbin", nameAr: "شربين" },
  { gov: "04", name: "Mataria", nameAr: "المطرية" },
  { gov: "04", name: "Belqas", nameAr: "بلقاس" },
  { gov: "04", name: "Meet Salsil", nameAr: "ميت سلسيل" },
  { gov: "04", name: "Gamasa", nameAr: "جمصة" },
  { gov: "04", name: "Mahalat Damana", nameAr: "محلة دمنة" },
  { gov: "04", name: "Nabroh", nameAr: "نبروه" },
  { gov: "05", name: "Hurghada", nameAr: "الغردقة" },
  { gov: "05", name: "Ras Ghareb", nameAr: "رأس غارب" },
  { gov: "05", name: "Safaga", nameAr: "سفاجا" },
  { gov: "05", name: "El Qusiar", nameAr: "القصير" },
  { gov: "05", name: "Marsa Alam", nameAr: "مرسى علم" },
  { gov: "05", name: "Shalatin", nameAr: "الشلاتين" },
  { gov: "05", name: "Halaib", nameAr: "حلايب" },
  { gov: "05", name: "Aldahar", nameAr: "الدهار" },
  { gov: "06", name: "Damanhour", nameAr: "دمنهور" },
  { gov: "06", name: "Kafr El Dawar", nameAr: "كفر الدوار" },
  { gov: "06", name: "Rashid", nameAr: "رشيد" },
  { gov: "06", name: "Edco", nameAr: "إدكو" },
  { gov: "06", name: "Abu al-Matamir", nameAr: "أبو المطامير" },
  { gov: "06", name: "Abu Homs", nameAr: "أبو حمص" },
  { gov: "06", name: "Delengat", nameAr: "الدلنجات" },
  { gov: "06", name: "Mahmoudiyah", nameAr: "المحمودية" },
  { gov: "06", name: "Rahmaniyah", nameAr: "الرحمانية" },
  { gov: "06", name: "Itai Baroud", nameAr: "إيتاي البارود" },
  { gov: "06", name: "Housh Eissa", nameAr: "حوش عيسى" },
  { gov: "06", name: "Shubrakhit", nameAr: "شبراخيت" },
  { gov: "06", name: "Kom Hamada", nameAr: "كوم حمادة" },
  { gov: "06", name: "Badr", nameAr: "بدر" },
  { gov: "06", name: "Wadi Natrun", nameAr: "وادي النطرون" },
  { gov: "06", name: "New Nubaria", nameAr: "النوبارية الجديدة" },
  { gov: "06", name: "Alnoubareya", nameAr: "النوبارية" },
  { gov: "07", name: "Fayoum", nameAr: "الفيوم" },
  { gov: "07", name: "Fayoum El Gedida", nameAr: "الفيوم الجديدة" },
  { gov: "07", name: "Tamiya", nameAr: "طامية" },
  { gov: "07", name: "Snores", nameAr: "سنورس" },
  { gov: "07", name: "Etsa", nameAr: "إطسا" },
  { gov: "07", name: "Epschway", nameAr: "إبشواي" },
  { gov: "07", name: "Yusuf El Sediaq", nameAr: "يوسف الصديق" },
  { gov: "07", name: "Hadqa", nameAr: "الحادقة" },
  { gov: "07", name: "Atsa", nameAr: "اطسا" },
  { gov: "07", name: "Algamaa", nameAr: "الجامعة" },
  { gov: "07", name: "Sayala", nameAr: "السيالة" },
  { gov: "08", name: "Tanta", nameAr: "طنطا" },
  { gov: "08", name: "Al Mahalla Al Kobra", nameAr: "المحلة الكبرى" },
  { gov: "08", name: "Kafr El Zayat", nameAr: "كفر الزيات" },
  { gov: "08", name: "Zefta", nameAr: "زفتى" },
  { gov: "08", name: "El Santa", nameAr: "السنطة" },
  { gov: "08", name: "Qutour", nameAr: "قطور" },
  { gov: "08", name: "Basion", nameAr: "بسيون" },
  { gov: "08", name: "Samannoud", nameAr: "سمنود" },
  { gov: "09", name: "Ismailia", nameAr: "الإسماعيلية" },
  { gov: "09", name: "Fayed", nameAr: "فايد" },
  { gov: "09", name: "Qantara Sharq", nameAr: "القنطرة شرق" },
  { gov: "09", name: "Qantara Gharb", nameAr: "القنطرة غرب" },
  { gov: "09", name: "El Tal El Kabier", nameAr: "التل الكبير" },
  { gov: "09", name: "Abu Sawir", nameAr: "أبو صوير" },
  { gov: "09", name: "Kasasien El Gedida", nameAr: "القصاصين الجديدة" },
  { gov: "09", name: "Nefesha", nameAr: "نفيشة" },
  { gov: "09", name: "Sheikh Zayed", nameAr: "الشيخ زايد" },
  { gov: "10", name: "Shbeen El Koom", nameAr: "شبين الكوم" },
  { gov: "10", name: "Sadat City", nameAr: "مدينة السادات" },
  { gov: "10", name: "Menouf", nameAr: "منوف" },
  { gov: "10", name: "Sars El-Layan", nameAr: "سرس الليان" },
  { gov: "10", name: "Ashmon", nameAr: "أشمون" },
  { gov: "10", name: "Al Bagor", nameAr: "الباجور" },
  { gov: "10", name: "Quesna", nameAr: "قويسنا" },
  { gov: "10", name: "Berkat El Saba", nameAr: "بركة السبع" },
  { gov: "10", name: "Tala", nameAr: "تلا" },
  { gov: "10", name: "Al Shohada", nameAr: "الشهداء" },
  { gov: "11", name: "Minya", nameAr: "المنيا" },
  { gov: "11", name: "Minya El Gedida", nameAr: "المنيا الجديدة" },
  { gov: "11", name: "El Adwa", nameAr: "العدوة" },
  { gov: "11", name: "Magagha", nameAr: "مغاغة" },
  { gov: "11", name: "Bani Mazar", nameAr: "بني مزار" },
  { gov: "11", name: "Mattay", nameAr: "مطاي" },
  { gov: "11", name: "Samalut", nameAr: "سمالوط" },
  { gov: "11", name: "Madinat El Fekria", nameAr: "المدينة الفكرية" },
  { gov: "11", name: "Meloy", nameAr: "ملوي" },
  { gov: "11", name: "Deir Mawas", nameAr: "دير مواس" },
  { gov: "11", name: "Abu Qurqas", nameAr: "ابو قرقاص" },
  { gov: "11", name: "Ard Sultan", nameAr: "ارض سلطان" },
  { gov: "12", name: "Banha", nameAr: "بنها" },
  { gov: "12", name: "Qalyub", nameAr: "قليوب" },
  { gov: "12", name: "Shubra Al Khaimah", nameAr: "شبرا الخيمة" },
  { gov: "12", name: "Al Qanater Charity", nameAr: "القناطر الخيرية" },
  { gov: "12", name: "Khanka", nameAr: "الخانكة" },
  { gov: "12", name: "Kafr Shukr", nameAr: "كفر شكر" },
  { gov: "12", name: "Tukh", nameAr: "طوخ" },
  { gov: "12", name: "Qaha", nameAr: "قها" },
  { gov: "12", name: "Obour", nameAr: "العبور" },
  { gov: "12", name: "Khosous", nameAr: "الخصوص" },
  { gov: "12", name: "Shibin Al Qanater", nameAr: "شبين القناطر" },
  { gov: "12", name: "Mostorod", nameAr: "مسطرد" },
  { gov: "13", name: "El Kharga", nameAr: "الخارجة" },
  { gov: "13", name: "Paris", nameAr: "باريس" },
  { gov: "13", name: "Mout", nameAr: "موط" },
  { gov: "13", name: "Farafra", nameAr: "الفرافرة" },
  { gov: "13", name: "Balat", nameAr: "بلاط" },
  { gov: "13", name: "Dakhla", nameAr: "الداخلة" },
  { gov: "14", name: "Suez", nameAr: "السويس" },
  { gov: "14", name: "Alganayen", nameAr: "الجناين" },
  { gov: "14", name: "Ataqah", nameAr: "عتاقة" },
  { gov: "14", name: "Ain Sokhna", nameAr: "العين السخنة" },
  { gov: "14", name: "Faysal", nameAr: "فيصل" },
  { gov: "15", name: "Aswan", nameAr: "أسوان" },
  { gov: "15", name: "Aswan El Gedida", nameAr: "أسوان الجديدة" },
  { gov: "15", name: "Drau", nameAr: "دراو" },
  { gov: "15", name: "Kom Ombo", nameAr: "كوم أمبو" },
  { gov: "15", name: "Nasr Al Nuba", nameAr: "نصر النوبة" },
  { gov: "15", name: "Kalabsha", nameAr: "كلابشة" },
  { gov: "15", name: "Edfu", nameAr: "إدفو" },
  { gov: "15", name: "Al-Radisiyah", nameAr: "الرديسية" },
  { gov: "15", name: "Al Basilia", nameAr: "البصيلية" },
  { gov: "15", name: "Al Sibaeia", nameAr: "السباعية" },
  { gov: "15", name: "Abo Simbl Al Siyahia", nameAr: "ابوسمبل السياحية" },
  { gov: "15", name: "Marsa Alam", nameAr: "مرسى علم" },
  { gov: "16", name: "Assiut", nameAr: "أسيوط" },
  { gov: "16", name: "Assiut El Gedida", nameAr: "أسيوط الجديدة" },
  { gov: "16", name: "Dayrout", nameAr: "ديروط" },
  { gov: "16", name: "Manfalut", nameAr: "منفلوط" },
  { gov: "16", name: "Qusiya", nameAr: "القوصية" },
  { gov: "16", name: "Abnoub", nameAr: "أبنوب" },
  { gov: "16", name: "Abu Tig", nameAr: "أبو تيج" },
  { gov: "16", name: "El Ghanaim", nameAr: "الغنايم" },
  { gov: "16", name: "Sahel Selim", nameAr: "ساحل سليم" },
  { gov: "16", name: "El Badari", nameAr: "البداري" },
  { gov: "16", name: "Sidfa", nameAr: "صدفا" },
  { gov: "17", name: "Bani Sweif", nameAr: "بني سويف" },
  { gov: "17", name: "Beni Suef El Gedida", nameAr: "بني سويف الجديدة" },
  { gov: "17", name: "Al Wasta", nameAr: "الواسطى" },
  { gov: "17", name: "Naser", nameAr: "ناصر" },
  { gov: "17", name: "Ehnasia", nameAr: "إهناسيا" },
  { gov: "17", name: "beba", nameAr: "ببا" },
  { gov: "17", name: "Fashn", nameAr: "الفشن" },
  { gov: "17", name: "Somasta", nameAr: "سمسطا" },
  { gov: "17", name: "Alabbaseri", nameAr: "الاباصيرى" },
  { gov: "17", name: "Mokbel", nameAr: "مقبل" },
  { gov: "18", name: "PorSaid", nameAr: "بورسعيد" },
  { gov: "18", name: "Port Fouad", nameAr: "بورفؤاد" },
  { gov: "18", name: "Alarab", nameAr: "العرب" },
  { gov: "18", name: "Zohour", nameAr: "حى الزهور" },
  { gov: "18", name: "Alsharq", nameAr: "حى الشرق" },
  { gov: "18", name: "Aldawahi", nameAr: "حى الضواحى" },
  { gov: "18", name: "Almanakh", nameAr: "حى المناخ" },
  { gov: "18", name: "Mubarak", nameAr: "حى مبارك" },
  { gov: "19", name: "Damietta", nameAr: "دمياط" },
  { gov: "19", name: "New Damietta", nameAr: "دمياط الجديدة" },
  { gov: "19", name: "Ras El Bar", nameAr: "رأس البر" },
  { gov: "19", name: "Faraskour", nameAr: "فارسكور" },
  { gov: "19", name: "Zarqa", nameAr: "الزرقا" },
  { gov: "19", name: "alsaru", nameAr: "السرو" },
  { gov: "19", name: "alruwda", nameAr: "الروضة" },
  { gov: "19", name: "Kafr El-Batikh", nameAr: "كفر البطيخ" },
  { gov: "19", name: "Azbet Al Burg", nameAr: "عزبة البرج" },
  { gov: "19", name: "Meet Abou Ghalib", nameAr: "ميت أبو غالب" },
  { gov: "19", name: "Kafr Saad", nameAr: "كفر سعد" },
  { gov: "20", name: "Zagazig", nameAr: "الزقازيق" },
  { gov: "20", name: "Al Ashr Men Ramadan", nameAr: "العاشر من رمضان" },
  { gov: "20", name: "Minya Al Qamh", nameAr: "منيا القمح" },
  { gov: "20", name: "Belbeis", nameAr: "بلبيس" },
  { gov: "20", name: "Mashtoul El Souq", nameAr: "مشتول السوق" },
  { gov: "20", name: "Qenaiat", nameAr: "القنايات" },
  { gov: "20", name: "Abu Hammad", nameAr: "أبو حماد" },
  { gov: "20", name: "El Qurain", nameAr: "القرين" },
  { gov: "20", name: "Hehia", nameAr: "ههيا" },
  { gov: "20", name: "Abu Kabir", nameAr: "أبو كبير" },
  { gov: "20", name: "Faccus", nameAr: "فاقوس" },
  { gov: "20", name: "El Salihia El Gedida", nameAr: "الصالحية الجديدة" },
  { gov: "20", name: "Al Ibrahimiyah", nameAr: "الإبراهيمية" },
  { gov: "20", name: "Deirb Negm", nameAr: "ديرب نجم" },
  { gov: "20", name: "Kafr Saqr", nameAr: "كفر صقر" },
  { gov: "20", name: "Awlad Saqr", nameAr: "أولاد صقر" },
  { gov: "20", name: "Husseiniya", nameAr: "الحسينية" },
  { gov: "20", name: "san alhajar alqablia", nameAr: "صان الحجر القبلية" },
  { gov: "20", name: "Manshayat Abu Omar", nameAr: "منشأة أبو عمر" },
  { gov: "21", name: "Al Toor", nameAr: "الطور" },
  { gov: "21", name: "Sharm El-Shaikh", nameAr: "شرم الشيخ" },
  { gov: "21", name: "Dahab", nameAr: "دهب" },
  { gov: "21", name: "Nuweiba", nameAr: "نويبع" },
  { gov: "21", name: "Taba", nameAr: "طابا" },
  { gov: "21", name: "Saint Catherine", nameAr: "سانت كاترين" },
  { gov: "21", name: "Abu Redis", nameAr: "أبو رديس" },
  { gov: "21", name: "Abu Zenaima", nameAr: "أبو زنيمة" },
  { gov: "21", name: "Ras Sidr", nameAr: "رأس سدر" },
  { gov: "22", name: "Kafr El Sheikh", nameAr: "كفر الشيخ" },
  { gov: "22", name: "Kafr El Sheikh Downtown", nameAr: "وسط البلد كفر الشيخ" },
  { gov: "22", name: "Desouq", nameAr: "دسوق" },
  { gov: "22", name: "Fooh", nameAr: "فوه" },
  { gov: "22", name: "Metobas", nameAr: "مطوبس" },
  { gov: "22", name: "Burg Al Burullus", nameAr: "برج البرلس" },
  { gov: "22", name: "Baltim", nameAr: "بلطيم" },
  { gov: "22", name: "Masief Baltim", nameAr: "مصيف بلطيم" },
  { gov: "22", name: "Hamol", nameAr: "الحامول" },
  { gov: "22", name: "Bella", nameAr: "بيلا" },
  { gov: "22", name: "Riyadh", nameAr: "الرياض" },
  { gov: "22", name: "Sidi Salm", nameAr: "سيدي سالم" },
  { gov: "22", name: "Qellen", nameAr: "قلين" },
  { gov: "22", name: "Sidi Ghazi", nameAr: "سيدي غازي" },
  { gov: "23", name: "Marsa Matrouh", nameAr: "مرسى مطروح" },
  { gov: "23", name: "El Hamam", nameAr: "الحمام" },
  { gov: "23", name: "Alamein", nameAr: "العلمين" },
  { gov: "23", name: "Dabaa", nameAr: "الضبعة" },
  { gov: "23", name: "Al-Nagila", nameAr: "النجيلة" },
  { gov: "23", name: "Sidi Brani", nameAr: "سيدي براني" },
  { gov: "23", name: "Salloum", nameAr: "السلوم" },
  { gov: "23", name: "Siwa", nameAr: "سيوة" },
  { gov: "23", name: "Marina", nameAr: "مارينا" },
  { gov: "23", name: "North Coast", nameAr: "الساحل الشمالى" },
  { gov: "24", name: "Luxor", nameAr: "الأقصر" },
  { gov: "24", name: "New Luxor", nameAr: "الأقصر الجديدة" },
  { gov: "24", name: "Esna", nameAr: "إسنا" },
  { gov: "24", name: "New Tiba", nameAr: "طيبة الجديدة" },
  { gov: "24", name: "Al ziynia", nameAr: "الزينية" },
  { gov: "24", name: "Al Bayadieh", nameAr: "البياضية" },
  { gov: "24", name: "Al Qarna", nameAr: "القرنة" },
  { gov: "24", name: "Armant", nameAr: "أرمنت" },
  { gov: "24", name: "Al Tud", nameAr: "الطود" },
  { gov: "25", name: "Qena", nameAr: "قنا" },
  { gov: "25", name: "New Qena", nameAr: "قنا الجديدة" },
  { gov: "25", name: "Abu Tesht", nameAr: "ابو طشت" },
  { gov: "25", name: "Nag Hammadi", nameAr: "نجع حمادي" },
  { gov: "25", name: "Deshna", nameAr: "دشنا" },
  { gov: "25", name: "Alwaqf", nameAr: "الوقف" },
  { gov: "25", name: "Qaft", nameAr: "قفط" },
  { gov: "25", name: "Naqada", nameAr: "نقادة" },
  { gov: "25", name: "Farshout", nameAr: "فرشوط" },
  { gov: "25", name: "Quos", nameAr: "قوص" },
  { gov: "26", name: "Arish", nameAr: "العريش" },
  { gov: "26", name: "Sheikh Zowaid", nameAr: "الشيخ زويد" },
  { gov: "26", name: "Nakhl", nameAr: "نخل" },
  { gov: "26", name: "Rafah", nameAr: "رفح" },
  { gov: "26", name: "Bir al-Abed", nameAr: "بئر العبد" },
  { gov: "26", name: "Al Hasana", nameAr: "الحسنة" },
  { gov: "27", name: "Sohag", nameAr: "سوهاج" },
  { gov: "27", name: "Sohag El Gedida", nameAr: "سوهاج الجديدة" },
  { gov: "27", name: "Akhmeem", nameAr: "أخميم" },
  { gov: "27", name: "Akhmim El Gedida", nameAr: "أخميم الجديدة" },
  { gov: "27", name: "Albalina", nameAr: "البلينا" },
  { gov: "27", name: "El Maragha", nameAr: "المراغة" },
  { gov: "27", name: "almunsha'a", nameAr: "المنشأة" },
  { gov: "27", name: "Dar AISalaam", nameAr: "دار السلام" },
  { gov: "27", name: "Gerga", nameAr: "جرجا" },
  { gov: "27", name: "Jahina Al Gharbia", nameAr: "جهينة الغربية" },
  { gov: "27", name: "Saqilatuh", nameAr: "ساقلته" },
  { gov: "27", name: "Tama", nameAr: "طما" },
  { gov: "27", name: "Tahta", nameAr: "طهطا" },
  { gov: "27", name: "Alkawthar", nameAr: "الكوثر" },
];

/**
 * Idempotent seed — safe to run multiple times.
 * Requires governorates to be seeded first (matches on `Governorate.code`).
 * Matches each city on the composite unique [governorateId, name].
 */
export async function seedCities(prisma: PrismaClient): Promise<void> {
  console.log(`\nSeeding ${CITIES.length} cities...`);

  const governorates = await prisma.governorate.findMany({
    select: { id: true, code: true },
  });
  const idByCode = new Map(governorates.map((g) => [g.code, g.id]));

  let created = 0;
  let updated = 0;

  for (const c of CITIES) {
    const governorateId = idByCode.get(c.gov);
    if (!governorateId) {
      throw new Error(
        `Governorate with code "${c.gov}" not found. Seed governorates first.`,
      );
    }

    const existing = await prisma.city.findUnique({
      where: {
        governorateId_name: { governorateId, name: c.name },
      },
      select: { id: true },
    });

    await prisma.city.upsert({
      where: {
        governorateId_name: { governorateId, name: c.name },
      },
      update: { nameAr: c.nameAr, isActive: true },
      create: {
        name: c.name,
        nameAr: c.nameAr,
        isActive: true,
        governorateId,
      },
    });

    if (existing) updated++;
    else created++;
  }

  console.log(`Cities seeded successfully! (${created} created, ${updated} updated)`);
}
