export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  MANAGER = 'MANAGER',
  REVIEWER = 'REVIEWER',
  USER = 'USER',
  VIEWER = 'VIEWER',
  REPRESENTATIVE = 'REPRESENTATIVE',
}
